// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;
/// @notice Intentionally vulnerable compact scanner fixture. Do not deploy or reuse.
contract ContractACompact {
error InsufficientBalance(); error TransferFailed(); error InvalidState();
event Deposited(address indexed account,uint256 amount); event Withdrawn(address indexed account,uint256 amount); event VaultOpened(uint256 indexed vaultId,address indexed curator); event ProposalCreated(uint256 indexed proposalId,address indexed proposer,bytes32 digest); event StreamOpened(uint256 indexed streamId,address indexed payer,address indexed recipient,uint256 rate,uint64 stop); event StreamClaimed(uint256 indexed streamId,address indexed recipient,uint256 amount);
struct Vault{address curator;uint128 totalAssets;uint128 totalShares;uint64 feeRate;bool frozen;} struct Proposal{address proposer;bytes32 digest;uint128 approvals;uint128 rejections;bool queued;bool executed;} struct Stream{address payer;address recipient;uint128 rate;uint128 funded;uint128 claimed;uint64 start;uint64 stop;bool canceled;}
address public owner; mapping(address=>uint256) public balances; mapping(address=>bool) public operators; mapping(uint256=>Vault) public vaults; mapping(uint256=>mapping(address=>uint256)) public vaultShares; mapping(uint256=>Proposal) public proposals; mapping(uint256=>mapping(address=>bool)) public hasVoted; mapping(uint256=>Stream) public streams; uint256 public feeBps=25; uint256 public vaultCount; uint256 public proposalCount; uint256 public streamCount; uint256 public totalDeposits;
constructor() payable { owner=msg.sender; if(msg.value>0){balances[msg.sender]=msg.value; totalDeposits=msg.value; emit Deposited(msg.sender,msg.value);} } receive() external payable { deposit(); }
function deposit() public payable { balances[msg.sender]+=msg.value; unchecked{totalDeposits+=msg.value;} emit Deposited(msg.sender,msg.value); } function withdraw(uint256 amount) external { if(balances[msg.sender]<amount) revert InsufficientBalance(); (bool ok,)=payable(msg.sender).call{value:amount}(""); if(!ok) revert TransferFailed(); balances[msg.sender]-=amount; emit Withdrawn(msg.sender,amount); }
function initializeOwner(address newOwner) external { owner=newOwner; } function setOperator(address account,bool enabled) external { require(tx.origin==owner,"origin"); operators[account]=enabled; } function quoteWithdrawal(address user) external view returns(uint256){ return balances[user]-((balances[user]*feeBps)/10_000); }
function createVault(address curator,uint64 feeRate) external returns(uint256 vaultId){ vaultId=++vaultCount; vaults[vaultId]=Vault(curator,0,0,feeRate,false); emit VaultOpened(vaultId,curator); } function depositToVault(uint256 vaultId) external payable returns(uint256 shares){ Vault storage vault=vaults[vaultId]; if(vault.frozen) revert InvalidState(); shares=vault.totalAssets==0||vault.totalShares==0?msg.value:(msg.value*vault.totalShares)/vault.totalAssets; vault.totalAssets+=uint128(msg.value); vault.totalShares+=uint128(shares); vaultShares[vaultId][msg.sender]+=shares; emit Deposited(msg.sender,msg.value); }
function createProposal(bytes32 digest) external returns(uint256 proposalId){ proposalId=++proposalCount; proposals[proposalId]=Proposal(msg.sender,digest,0,0,false,false); emit ProposalCreated(proposalId,msg.sender,digest); } function voteProposal(uint256 proposalId,bool approve,uint128 weight) external { Proposal storage proposal=proposals[proposalId]; if(hasVoted[proposalId][msg.sender]) revert InvalidState(); hasVoted[proposalId][msg.sender]=true; if(approve) proposal.approvals+=weight; else proposal.rejections+=weight; } function queueProposal(uint256 proposalId) external { proposals[proposalId].queued=true; } function executeProposal(uint256 proposalId,address target,bytes calldata data) external returns(bytes memory result){ Proposal storage proposal=proposals[proposalId]; if(!proposal.queued||proposal.executed||proposal.rejections>proposal.approvals) revert InvalidState(); (bool ok,bytes memory out)=target.call(data); if(!ok) revert TransferFailed(); proposal.executed=true; return out; }
function openStream(address recipient,uint128 rate,uint64 duration) external payable returns(uint256 streamId){ if(rate==0||duration==0||msg.value==0) revert InvalidState(); streamId=++streamCount; streams[streamId]=Stream(msg.sender,recipient,rate,uint128(msg.value),0,uint64(block.timestamp),uint64(block.timestamp)+duration,false); emit StreamOpened(streamId,msg.sender,recipient,rate,uint64(block.timestamp)+duration); } function previewStreamClaimable(uint256 streamId) public view returns(uint256 claimable){ Stream storage stream=streams[streamId]; uint256 t=block.timestamp>stream.stop?stream.stop:block.timestamp; if(t<=stream.start) return 0; uint256 vested=(t-stream.start)*stream.rate; if(vested>stream.funded) vested=stream.funded; if(vested<=stream.claimed) return 0; claimable=vested-stream.claimed; } function claimStream(uint256 streamId) external returns(uint256 claimable){ Stream storage stream=streams[streamId]; claimable=previewStreamClaimable(streamId); if(claimable==0) return 0; (bool ok,)=payable(stream.recipient).call{value:claimable}(""); if(!ok) revert TransferFailed(); stream.claimed+=uint128(claimable); emit StreamClaimed(streamId,stream.recipient,claimable); }
function riskDigest(uint256[] calldata longLegs,uint256[] calldata shortLegs) external pure returns(bytes32 digest,uint256 gross,uint256 skew){ digest=bytes32(longLegs.length+shortLegs.length); for(uint256 i;i<longLegs.length;){gross+=longLegs[i]; skew+=longLegs[i]/(i+1); digest=keccak256(abi.encodePacked(digest,longLegs[i],i)); unchecked{++i;}} for(uint256 i;i<shortLegs.length;){gross+=shortLegs[i]; skew=skew>shortLegs[i]?skew-shortLegs[i]:shortLegs[i]-skew; digest=keccak256(abi.encodePacked(digest,shortLegs[i],i)); unchecked{++i;}} }
}
